"https://thepiratebay.org/description.php?id="
avascript:(function(){const query="https://thepiratebay.org/description.php?id=";const links=document.querySelectorAll("a");let matches=[];links.forEach(link=>{const href=link.href||link.getAttribute("href");if(href&&href.includes(query)){matches.push(href);}});const old=document.getElementById("linkModal");if(old)old.remove();const modal=document.createElement("div");modal.id="linkModal";modal.style="position:fixed;top:20%;left:50%;transform:translateX(-50%);background:#fff;border:1px solid #333;padding:10px;z-index:9999;max-width:80%;max-height:60%;overflow:auto;";const btnBar=document.createElement("div");btnBar.style="margin-bottom:10px;";const copyBtn=document.createElement("button");copyBtn.textContent="Copy to Clipboard";copyBtn.onclick=function(){navigator.clipboard.writeText(matches.join('\n')).then(()=>{msg.textContent='✅ Links copied to clipboard!';});};btnBar.appendChild(copyBtn);const closeBtn=document.createElement("button");closeBtn.textContent="Close";closeBtn.style.marginLeft="10px";closeBtn.onclick=function(){modal.remove();};btnBar.appendChild(closeBtn);modal.appendChild(btnBar);const msg=document.createElement("div");msg.style="margin:5px 0;color:green;font-weight:bold;";modal.appendChild(msg);const title=document.createElement("h3");title.textContent="Links containing 'id='";modal.appendChild(title);const list=document.createElement("pre");list.textContent=matches.length>0?matches.join('\n'):"No links found.";modal.appendChild(list);document.body.appendChild(modal);})();


//if(href.includes("id=")||href.includes("?id")||href.includes("&id")||href.includes("=")){matches.push(href);}
avascript:(function(){const query="https://thepiratebay.org/description.php?id=";const links=document.querySelectorAll("a[href]");let matches=[];let allLinks=[];links.forEach(link=>{const href=link.href||link.getAttribute("href");if(href){allLinks.push(href);if(href.includes(query)){matches.push(href);}}});const old=document.getElementById("linkModal");if(old)old.remove();const modal=document.createElement("div");modal.id="linkModal";modal.style.cssText="position:fixed;top:10%;left:50%;transform:translateX(-50%);background:#1a2a3a;border:1px solid #4a7a9a;padding:20px;z-index:99999;max-width:90%;max-height:80%;overflow:auto;border-radius:12px;color:#d6edff;box-shadow:0 10px 40px rgba(0,0,0,0.8);font-family:Segoe UI,sans-serif;min-width:400px;";const btnBar=document.createElement("div");btnBar.style.cssText="margin-bottom:12px;display:flex;gap:10px;flex-wrap:wrap;";const copyBtn=document.createElement("button");copyBtn.textContent="📋 Copy id= links";copyBtn.style.cssText="background:#2a5a7a;border:none;color:white;padding:8px 16px;border-radius:8px;cursor:pointer;";copyBtn.onclick=function(){navigator.clipboard.writeText(matches.join("\n")).then(()=>{msg.textContent="✅ Copied "+matches.length+" links!";});};btnBar.appendChild(copyBtn);const closeBtn=document.createElement("button");closeBtn.textContent="✕ Close";closeBtn.style.cssText="background:#5a2a2a;border:none;color:white;padding:8px 16px;border-radius:8px;cursor:pointer;";closeBtn.onclick=function(){modal.remove();};btnBar.appendChild(closeBtn);modal.appendChild(btnBar);const msg=document.createElement("div");msg.style.cssText="margin:5px 0;color:#80d080;font-weight:bold;";modal.appendChild(msg);const stats=document.createElement("div");stats.style.cssText="margin:5px 0 10px;color:#b0d0e0;font-size:13px;";stats.textContent="Found "+matches.length+" links containing 'id=' | Total links: "+allLinks.length;modal.appendChild(stats);const title=document.createElement("h3");title.textContent="🔗 Links containing 'id='";title.style.cssText="margin:8px 0;color:#b0d8f0;";modal.appendChild(title);const list=document.createElement("pre");list.textContent=matches.length>0?matches.join("\n"):"No links found containing 'id='";list.style.cssText="background:#0b1a2a;padding:12px;border-radius:8px;max-height:300px;overflow:auto;color:#b0d0e0;font-size:12px;white-space:pre-wrap;word-break:break-all;";modal.appendChild(list);document.body.appendChild(modal);})();


http://ikeanangelsaidthe.com/redirect?tid=855295
http://ikeanangelsaidthe.com/redirect?tid=855295



"https://thepiratebay.org/description.php?id="



//document write
avascript:(function(){
	const query="https://thepiratebay.org/description.php?id=";
  const links = document.querySelectorAll("a[href]");
  let allLinks = [];
  links.forEach(link => {
    const href = link.href || link.getAttribute("href");
    if(href&&href.includes(query)) allLinks.push(href);
  });
  document.write("<h3>🔗 All Links Found</h3><pre style='white-space:pre-wrap;word-break:break-all;font-family:Segoe UI,sans-serif;'>"
    + (allLinks.length > 0 ? allLinks.join("\n") : "No links found")
    + "</pre>");
})();

//alert,not workin
avascript:(async function(){const query=prompt("Search term:")||"windows";const base="https://thepiratebay.org/search/";const fixed="/99/1";const limit=5;let allLinks=[];const urls=[];for(let i=1;i<=limit;i++){urls.push(base+query+"/"+i+fixed);}const results=await Promise.all(urls.map(u=>fetch(u).then(r=>r.text()).catch(()=>null)));results.forEach(html=>{if(!html)return;const doc=new DOMParser().parseFromString(html,"text/html");doc.querySelectorAll("a[href]").forEach(link=>{const href=link.href||link.getAttribute("href");if(href&&href.includes("description.php?id=")){allLinks.push(href);}});});document.write("<h3>🔗 Links Found Across Pages</h3><pre style='white-space:pre-wrap;word-break:break-all;font-family:Segoe UI,sans-serif;'>"+(allLinks.length>0?allLinks.join("\n"):"No links found")+"</pre>");})();






//second


//document.write
avascript:(function(){
	const query="https://thepiratebay.org/description.php?id=";
  const links=document.querySelectorAll("a[href]");
  let matches=[];
  links.forEach(link=>{
    const href=link.href||link.getAttribute("href");
    if(href && href.includes(query)){
      matches.push(href);
    }
  });
  const newWin=window.open("","_blank");
  newWin.document.write("<h3>🔗 Links Found</h3><pre style='white-space:pre-wrap;word-break:break-all;font-family:Segoe UI,sans-serif;'>extract all info for these links i mean id,name,size,magnet-link,hash,seeders,leechers and put all of them isinde object<p>"
    +(matches.length>0?matches.join("\n"):"No links found")
    +"</pre>");
})();






//new.window
avascript:(function(){const query="https://thepiratebay.org/description.php?id=";const links=document.querySelectorAll("a[href]");let matches=[];links.forEach(link=>{const href=link.href||link.getAttribute("href");if(href&&href.includes(query)){matches.push(href)}});const newWin=window.open("","_blank","width=700,height=500");if(newWin){newWin.document.write('<!DOCTYPE html><html><head><style>body{font-family:Segoe UI,sans-serif;background:#1a1a1a;color:#fff;padding:20px;margin:0}.header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;padding-bottom:10px;border-bottom:2px solid #00ff00;flex-wrap:wrap;gap:10px}.btn-group{display:flex;gap:10px}.copy-btn{background:#00ff00;color:#000;border:none;padding:10px 20px;border-radius:5px;cursor:pointer;font-weight:bold;font-size:14px}.copy-btn:hover{background:#00cc00}.copy-btn.copied{background:#ff8800;color:#fff}.close-btn{background:#ff4444;color:#fff;border:none;padding:10px 20px;border-radius:5px;cursor:pointer;font-weight:bold;font-size:14px}.close-btn:hover{background:#cc0000}.pre-wrap{white-space:pre-wrap;word-break:break-all;font-family:monospace;font-size:13px;background:#2a2a2a;padding:15px;border-radius:5px;max-height:70vh;overflow:auto;margin:0}.count{color:#00ff00;font-weight:bold}</style></head><body><div class="header"><h3 style="margin:0;">🔗 Links Found <span class="count">('+matches.length+')</span></h3><div class="btn-group"><button class="copy-btn" onclick="copyLinks()">📋 Copy All Links</button><button class="close-btn" onclick="window.close()">✕ Close</button></div></div><pre class="pre-wrap" id="linksList">'+(matches.length>0?matches.join("\n"):"No links found")+'</pre><script>function copyLinks(){const links=document.getElementById("linksList").textContent;navigator.clipboard.writeText(links).then(()=>{const btn=document.querySelector(".copy-btn");btn.textContent="✅ Copied!";btn.classList.add("copied");setTimeout(()=>{btn.textContent="📋 Copy All Links";btn.classList.remove("copied")},2000)}).catch(()=>{alert("Failed to copy. Please select and copy manually.")})}<\/script></body></html>');newWin.document.close()}else{alert("Popup blocked! Please allow popups.")}})();
avascript:(function(){const query="https://thepiratebay.org/description.php?id=";const links=document.querySelectorAll("a[href]");let matches=[];links.forEach(link=>{const href=link.href||link.getAttribute("href");if(href&&href.includes(query)){matches.push(href)}});const div=document.createElement('div');div.id='tpb-links';div.style.cssText='position:fixed;top:10px;right:10px;background:#1a1a1a;color:#fff;padding:20px;border-radius:10px;z-index:999999;max-width:500px;max-height:80vh;overflow:auto;font-family:Segoe UI,sans-serif;font-size:12px;border:2px solid #00ff00;box-shadow:0 0 30px rgba(0,255,0,0.2);min-width:300px;';div.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:15px;border-bottom:2px solid #00ff00;padding-bottom:10px;"><h3 style="margin:0;color:#fff;">🔗 Links (<span style="color:#00ff00;">'+matches.length+'</span>)</h3><div><button onclick="copyLinks()" style="background:#00ff00;color:#000;border:none;padding:5px 15px;border-radius:5px;cursor:pointer;font-weight:bold;font-size:14px;margin-right:8px;">📋 Copy</button><button onclick="closeDiv()" style="background:#ff4444;color:#fff;border:none;padding:5px 15px;border-radius:5px;cursor:pointer;font-weight:bold;font-size:14px;">✕ Close</button></div></div><pre id="tpb-links-content" style="white-space:pre-wrap;word-break:break-all;margin:0;font-family:monospace;font-size:12px;color:#00ff00;">'+(matches.length>0?matches.join("\n"):"No links found")+'</pre>';document.body.appendChild(div);window.copyLinks=function(){const links=document.getElementById('tpb-links-content').textContent;navigator.clipboard.writeText(links).then(()=>{const btn=document.querySelector('[onclick="copyLinks()"]');const origText=btn.textContent;btn.textContent="✅ Copied!";btn.style.background="#ff8800";btn.style.color="#fff";setTimeout(()=>{btn.textContent=origText;btn.style.background="#00ff00";btn.style.color="#000"},1500)}).catch(()=>{alert("Failed to copy. Please select and copy manually.")})};window.closeDiv=function(){const div=document.getElementById('tpb-links');if(div)document.body.removeChild(div)}})();



//alert
avascript:(function(){const query="https://thepiratebay.org/description.php?id=";const links=document.querySelectorAll("a[href]");let matches=[];links.forEach(link=>{const href=link.href||link.getAttribute("href");if(href&&href.includes(query)){matches.push(href)}});const div=document.createElement('div');div.id='tpb-links-float';div.style.cssText='position:fixed;top:10px;right:10px;background:#1a1a1a;color:#fff;padding:20px;border-radius:10px;z-index:999999;max-width:500px;max-height:80vh;overflow:auto;font-family:Segoe UI,sans-serif;font-size:12px;border:2px solid #00ff00;box-shadow:0 0 30px rgba(0,255,0,0.2);min-width:300px;';div.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:15px;border-bottom:2px solid #00ff00;padding-bottom:10px;"><h3 style="margin:0;color:#fff;font-size:14px;">🔗 Links Found (<span style="color:#00ff00;" id="linkCount">'+matches.length+'</span>)</h3><div><button onclick="copyLinks()" style="background:#00ff00;color:#000;border:none;padding:6px 12px;border-radius:5px;cursor:pointer;font-weight:bold;font-size:12px;margin-right:8px;">📋 Copy</button><button onclick="closeDiv()" style="background:#ff4444;color:#fff;border:none;padding:6px 12px;border-radius:5px;cursor:pointer;font-weight:bold;font-size:12px;">✕ Close</button></div></div><pre id="linksContent" style="white-space:pre-wrap;word-break:break-all;margin:0;font-family:monospace;font-size:12px;color:#00ff00;max-height:60vh;overflow:auto;">'+(matches.length>0?matches.join("\n"):"No links found")+'</pre>';document.body.appendChild(div);window.copyLinks=function(){const links=document.getElementById('linksContent').textContent;navigator.clipboard.writeText(links).then(()=>{const btn=document.querySelector('[onclick="copyLinks()"]');btn.textContent="✅ Copied!";btn.style.background="#ff8800";setTimeout(()=>{btn.textContent="📋 Copy";btn.style.background="#00ff00"},1500)}).catch(()=>{alert("Failed to copy. Please select and copy manually.")})};window.closeDiv=function(){const div=document.getElementById('tpb-links-float');if(div)document.body.removeChild(div)}})();

//document.w
avascript:(function(){const query="https://thepiratebay.org/description.php?id=";const links=document.querySelectorAll("a[href]");let matches=[];links.forEach(link=>{const href=link.href||link.getAttribute("href");if(href&&href.includes(query)){matches.push(href)}});document.body.innerHTML='';document.write('<!DOCTYPE html><html><head><style>body{font-family:Segoe UI,sans-serif;background:#1a1a1a;color:#fff;padding:20px;margin:0}.header{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;padding-bottom:10px;border-bottom:2px solid #00ff00;flex-wrap:wrap;gap:10px}.btn-group{display:flex;gap:10px}.copy-btn{background:#00ff00;color:#000;border:none;padding:10px 20px;border-radius:5px;cursor:pointer;font-weight:bold;font-size:14px}.copy-btn:hover{background:#00cc00}.copy-btn.copied{background:#ff8800;color:#fff}.close-btn{background:#ff4444;color:#fff;border:none;padding:10px 20px;border-radius:5px;cursor:pointer;font-weight:bold;font-size:14px}.close-btn:hover{background:#cc0000}.pre-wrap{white-space:pre-wrap;word-break:break-all;font-family:monospace;font-size:13px;background:#2a2a2a;padding:15px;border-radius:5px;max-height:80vh;overflow:auto;margin:0}.count{color:#00ff00;font-weight:bold}</style></head><body><div class="header"><h3 style="margin:0;">🔗 Links Found <span class="count">('+matches.length+')</span></h3><div class="btn-group"><button class="copy-btn" onclick="copyLinks()">📋 Copy All Links</button><button class="close-btn" onclick="goBack()">✕ Close</button></div></div><pre class="pre-wrap" id="linksList">'+(matches.length>0?matches.join("\n"):"No links found")+'</pre><script>function copyLinks(){const links=document.getElementById("linksList").textContent;navigator.clipboard.writeText(links).then(()=>{const btn=document.querySelector(".copy-btn");btn.textContent="✅ Copied!";btn.classList.add("copied");setTimeout(()=>{btn.textContent="📋 Copy All Links";btn.classList.remove("copied")},2000)}).catch(()=>{alert("Failed to copy. Please select and copy manually.")})}function goBack(){history.back()}<\/script></body></html>');})();

//new window
avascript:(function(){const query="https://thepiratebay.org/description.php?id=";const links=document.querySelectorAll("a[href]");let matches=[];links.forEach(link=>{const href=link.href||link.getAttribute("href");if(href&&href.includes(query)){matches.push(href)}});const newWin=window.open("","_blank","width=600,height=400");if(newWin){newWin.document.write("<h3>🔗 Links Found</h3><pre style='white-space:pre-wrap;word-break:break-all;font-family:Segoe UI,sans-serif;'>"+(matches.length>0?matches.join("\n"):"No links found")+"</pre>");newWin.document.close()}else{alert("Popup blocked! Please allow popups.")}})();
avascript:(function(){const query="https://thepiratebay.org/description.php?id=";const links=document.querySelectorAll("a[href]");let matches=[];links.forEach(link=>{const href=link.href||link.getAttribute("href");if(href&&href.includes(query)){matches.push(href)}});const div=document.createElement('div');div.id='tpb-links';div.style.cssText='position:fixed;top:10px;right:10px;background:#1a1a1a;color:#fff;padding:20px;border-radius:10px;z-index:999999;max-width:500px;max-height:80vh;overflow:auto;font-family:Segoe UI,sans-serif;font-size:12px;border:2px solid #00ff00;box-shadow:0 0 30px rgba(0,255,0,0.2);min-width:300px;';div.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:15px;border-bottom:2px solid #00ff00;padding-bottom:10px;"><h3 style="margin:0;color:#fff;">🔗 Links (<span style="color:#00ff00;">'+matches.length+'</span>)</h3><div><button onclick="copyLinks()" style="background:#00ff00;color:#000;border:none;padding:5px 15px;border-radius:5px;cursor:pointer;font-weight:bold;font-size:14px;margin-right:8px;">📋 Copy</button><button onclick="closeDiv()" style="background:#ff4444;color:#fff;border:none;padding:5px 15px;border-radius:5px;cursor:pointer;font-weight:bold;font-size:14px;">✕ Close</button></div></div><pre id="tpb-links-content" style="white-space:pre-wrap;word-break:break-all;margin:0;font-family:monospace;font-size:12px;color:#00ff00;">'+(matches.length>0?matches.join("\n"):"No links found")+'</pre>';document.body.appendChild(div);window.copyLinks=function(){const links=document.getElementById('tpb-links-content').textContent;navigator.clipboard.writeText(links).then(()=>{const btn=document.querySelector('[onclick="copyLinks()"]');const origText=btn.textContent;btn.textContent="✅ Copied!";btn.style.background="#ff8800";btn.style.color="#fff";setTimeout(()=>{btn.textContent=origText;btn.style.background="#00ff00";btn.style.color="#000"},1500)}).catch(()=>{alert("Failed to copy.")})};window.closeDiv=function(){const div=document.getElementById('tpb-links');if(div)document.body.removeChild(div)}})();